server:
  port: 8061
 
spring:
  application:
    name:  eureka-server

logging:
  info: info


security:
  basic:
    enabled: false
  user:
    name: gmall
    password: gmall123



eureka:
  instance:
    hostname: eureka8061.comm
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
